appearances=cube-bot,actor,construction,professional
cube-bot=/bot-appearance/Cube-Bot.iar
actor.male=/bot-appearance/Actor-Male.iar
actor.female=/bot-appearance/Actor-Female.iar
construction.male=/bot-appearance/Construction-Male.iar
construction.female=/bot-appearance/Construction-Female.iar
professional.male=/bot-appearance/Professional-Man.iar
professional.female=/bot-appearance/Professional-Woman.iar