server.address=${OPENSIM_SPAWNER_HTTP_HOST:0.0.0.0}
server.port=${OPENSIM_SPAWNER_HTTP_PORT:8993}

spawner.token=${OPENSIM_SPAWNER_TOKEN:}
spawner.first-port=${OPENSIM_SPAWNER_FIRST_PORT:12345}
spawner.metaverse2mcp-image=${OPENSIM_METAVERSE2MCP_IMAGE:bithatch/opensim-metaverse2mcp:latest}
spawner.opencode-image=${OPENSIM_OPENCODE_IMAGE:bithatch/opensim-opencode:latest}
spawner.open-code-handler-firstname=${OPENSIM_BOT_HANDLER_FIRSTNAME:}
spawner.open-code-handler-lastname=${OPENSIM_BOT_HANDLER_LASTNAME:}
spawner.opensim-console-url=${OPENSIM_CONSOLE_URL:http://opensim:9000}
spawner.opensim-console-user=${OPENSIM_CONSOLE_USER:}
spawner.opensim-console-pass=${OPENSIM_CONSOLE_PASS:}

spawner.opensim-create-bot-user=${OPENSIM_CREATE_BOT_USER:true}
spawner.opensim-login-firstname=${OPENSIM_LOGIN_FIRSTNAME:-Bot}
spawner.opensim-login-lastname=${OPENSIM_LOGIN_LASTNAME:-User}
spawner.opensim-login-email=${OPENSIM_LOGIN_EMAIL:-bot@localhost}
spawner.opensim-login-model=${OPENSIM_LOGIN_MODEL:-Ruth}
spawner.opensim-spawner-max-box=${OPENSIM_SPAWNER_MAX_BOTS:-10}
spawner.opensim-pull-policy=${OPENSIM_PULL_POLICY:-missing}
spawner.opensim-restart-policy=${OPENSIM_RESTART_POLICY:-unless-stopped}
spawner.opensim-network=${OPENSIM_NETWORK:-opensim-ai-docker_default}
spawner.compose-project-name=${COMPOSE_PROJECT_NAME:}
