oars=blank,sandbox,shopping-center

blank=/oars/OAR-BlankSim(1X1).tgz
blank.name=Blank
blank.info=/oars/OAR-BlankSim(1X1).txt
blank.x=1
blank.y=1

sandbox=/oars/OAR-Sandbox(1X1).tgz
sandbox.name=Sandbox
sandbox.info=/oars/OAR-Sandbox(1X1).txt
sandbox.x=1
sandbox.y=1

shopping-center.name=Shopping Center
shopping-center=/oars/OAR-ShoppingCenter(1X1).tgz
shopping-center.info=/oars/OAR-ShoppingCenter(1X1).txt
shopping-center.x=1
shopping-center.y=1